### PR TITLE
Wmic fix

### PR DESCRIPTION
**Pull request by trlinkin**
When a big AD domain is present, things get slow...

I HOPE THIS HELPS! :)

### CODE REVIEW

**Comment by GerbenWelter** [comment]
Although the client I'm currently at doesn't use this module at the moment I decided to give this simple fix a try and the difference is like night and day. No more minutes of waiting and DDOS'ing the DC's :-D

**Comment by ayohrling** [comment]
@trlinkin @GerbenWelter My only concern here is that we've now removed the functionality of listing/verifying users that are placed from the domain. I'm not saying this module *should* be used that way, but it's possible that folks currently are using it in that manner. Perhaps we should make this optional for folks to be able to disable/enable domain lookups?

**Comment by trlinkin** [comment]
Either that or there should be some alternative method to lookup users that weren't mapped by this method. Do you know where in the codebase this sort of thing would be reasonable?

I'm leaning on the fact that this method is explicitly saying it will lookup "local users" in both name and comment seemed reasonable to me. Honestly, for anybody with a sufficiently large domain this is unusable in it'c current form. I don't have a domain to test, I was sort of just hoping there was an alternative method for lookups related to domain users. I could probably dig through the codebase a bit more.

Honestly, having this work quickly and needing to use SIDs is (in my opinion) better than the current state of things.

**Comment by trlinkin** [comment]
FWIW, looks like  https://github.com/ayohrling/local_security_policy/blob/v0.6.2/lib/puppet_x/lsp/security_policy.rb#L43 would be where we would want to add additional lookup in the event that a domain resolved user. Lets see if there are issues raised on this current release and address them as needed.

**Pull request merged**
