### PR TITLE
Make Event Audit work

### PR DESCRIPTION
**Pull request by mciurcio**
Small fixes to make Event Audit policies work properly.

* The split() method was being called on an Array.
* Typo in a variable name.
* Comparing strings against integers made the resources always out of sync.
* Avoid overwriting of the .inf files. I had a hard time doing debug because of it.

### CODE REVIEW

**Comment by logicminds** [comment]
Can you rebase, I just pushed a bunch of new work that I had been holding on to.  Also realized I had push access.

**Comment by logicminds** [comment]
The changes are now in a different file, and look to still be broken.

https://github.com/ayohrling/local_security_policy/blob/master/lib/puppet_x/lsp/security_policy.rb#L182

**Comment by mciurcio** [comment]
Your refactored code solves the problem. I'm closing this PR.

On Thu, Nov 19, 2015 at 12:11 PM, Corey Osman <notifications@github.com>
wrote:

> The changes are now in a different file, and look to still be broken.
>
>
> https://github.com/ayohrling/local_security_policy/blob/master/lib/puppet_x/lsp/security_policy.rb#L182
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayohrling/local_security_policy/pull/8#issuecomment-158068245>
> .
>



-- 
http://www.instruct.com.br - 19 2511-6506

**Comment by mciurcio** [comment]
That's odd.

**Pull request closed without merging**
